-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2024-10-16 19:25:46 BRT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



DROP TABLE tb_alerta_sensores CASCADE CONSTRAINTS;

DROP TABLE tb_alerta_sensores_npk CASCADE CONSTRAINTS;

DROP TABLE tb_sensor_npk CASCADE CONSTRAINTS;

DROP TABLE tb_sensor_umidade_e_pu CASCADE CONSTRAINTS;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE tb_alerta_sensores (
    alerta_id     INTEGER NOT NULL,
    sensor_id     INTEGER NOT NULL,
    tipo_sensor   VARCHAR2(50 CHAR) NOT NULL,
    data_alerta   DATE NOT NULL,
    tipo_alerta   VARCHAR2(50 CHAR) NOT NULL,
    valor_medido  NUMBER NOT NULL,
    status_alerta VARCHAR2(50 CHAR) NOT NULL
);

ALTER TABLE tb_alerta_sensores ADD CONSTRAINT pk_tb_alerta_sensores PRIMARY KEY ( alerta_id );

CREATE TABLE tb_alerta_sensores_npk (
    alerta_id     INTEGER NOT NULL,
    sensor_id     INTEGER NOT NULL,
    tipo_sensor   VARCHAR2(50 CHAR) NOT NULL,
    data_alerta   DATE NOT NULL,
    tipo_alerta   VARCHAR2(50 CHAR) NOT NULL,
    valor_medido  NUMBER NOT NULL,
    status_alerta VARCHAR2(50 CHAR) NOT NULL
);

ALTER TABLE tb_alerta_sensores_npk ADD CONSTRAINT pk_tb_alerta_sensores_npk PRIMARY KEY ( alerta_id );

CREATE TABLE tb_sensor_npk (
    sensor_id         INTEGER NOT NULL,
    tipo_sensor       VARCHAR2(50 CHAR) NOT NULL,
    localizacao       VARCHAR2(50 CHAR) NOT NULL,
    ultima_leitura    DATE NOT NULL,
    valor_nitrogenio  NUMBER NOT NULL,
    valor_fosforo     NUMBER NOT NULL,
    valor_potassio    NUMBER NOT NULL,
    status            VARCHAR2(50 CHAR) NOT NULL,
    bateria           NUMBER NOT NULL,
    faixa_operacional VARCHAR2(20 CHAR) NOT NULL
);

ALTER TABLE tb_sensor_npk ADD CONSTRAINT pk_tb_sensor_npk PRIMARY KEY ( sensor_id );

CREATE TABLE tb_sensor_umidade_e_pu (
    sensor_id      INTEGER NOT NULL,
    tipo_sensor    VARCHAR2(50 CHAR) NOT NULL,
    localizacao    VARCHAR2(50 CHAR) NOT NULL,
    ultima_leitura DATE NOT NULL,
    valor_leitura  NUMBER NOT NULL,
    status         VARCHAR2(50 CHAR) NOT NULL,
    bateria        NUMBER NOT NULL
);

ALTER TABLE tb_sensor_umidade_e_pu ADD CONSTRAINT pk_tb_sensor_umidade_e_pu PRIMARY KEY ( sensor_id );

ALTER TABLE tb_alerta_sensores_npk
    ADD CONSTRAINT fk_npk_tb_sensor_npk FOREIGN KEY ( sensor_id )
        REFERENCES tb_sensor_npk ( sensor_id );

ALTER TABLE tb_alerta_sensores
    ADD CONSTRAINT fk_umidade_e_pu FOREIGN KEY ( sensor_id )
        REFERENCES tb_sensor_umidade_e_pu ( sensor_id );
